### ISSUE TITLE
adding users to exports.auth

### ISSUE THREAD

**Issue by cpg** [mhils/gsoc-eval#4]
hi, once the app is deployed and there is live data on the server, and it's running, how does one add one user?

i.e. add (or delete) one username/password pair to the `exports.auth` entry in `data/config.js` .. but then how do i "push" that to the live server under docker and restart it to start accepting logins for those users? (without destroying data)

(may be a good thing to add to the README)

**Comment by mhils** [comment]
You adjust the file to your needs and then restart the app. :-) 
Docker containers can be stopped and started like this:
```
docker-compose stop
docker-compose up -d
```

**Comment by cpg** [comment]
one quick/small suggestion is to make the links in the top right of proposals open with `target=_blank`.

fantastic, thanks!

**Comment by mhils** [comment]
Fixed, thanks!

**Comment by cpg** [comment]
i wanted to make some style changes (e.g. usernames in comments be, say `#D70808` color) to make them more visible to the rest of the team, but app.css does not appear to be pushed with the stop + up -d. Is there are way to push that out?

Actually, that change to open in a separate tab does not appear to go through either after a pull + stop + up -d.

Sorry to bother you with these silly support questions.

**Comment by mhils** [comment]
Hey, no worries - a perfect opportunity to procrastinate.

I added dev instructions at https://github.com/mhils/gsoc-eval#development. Regarding the separate tab changes, see https://github.com/mhils/gsoc-eval#update. :)

**Comment by cpg** [comment]
thanks. that helps with local development. i have that working.

what happens when i want to deploy the changes? (assume for a moment that I have my own repo with my changes).

i tried to rebuild and did not work. ended up breaking things badly and i can't launch the server any more (all sort of errors with "device busy" and later as i tried to "down" and "stop" things with `ERROR: stat /var/lib/docker/overlay/93cbbfe0b44a06b09bbc337ccd161d9b5d16bfc1cad8a607a4c3a37e17c56e28: no such file or directory`).

assuming i get all this sorted out (new to docker itself), i want to be able to deploy changes **without** obliterating data. Or at the very least I want to be able to "extract" and back-up the comments and ratings, then later restore them before restarting the service.
