### ISSUE TITLE
Automatically update when proposals.json is updated

### ISSUE THREAD

**Issue by jayvdb** [mhils/gsoc-eval#7]
Listen for changes to `proposals.json` and reset relevant state.

Allows updates to the data file during pre-deadline period without restarting the server.

**Comment by mhils** [comment]
I'm still not convinced about the overall use case, but if it helps we can surely not cache the proposals and move the `jsonfile.readFileSync("./data/proposals.json")` call into `app.get('/proposals.json', ...)`. Does that work for you?
